var BenchConstants = {
  BENCHES_RECEIVED: "BENCHES_RECEIVED",
  BENCH_SELECTED: "BENCH_SELECTED",
  BENCH_UNSELECTED: "BENCH_UNSELECTED",
  BENCH_RECEIVED: "BENCH_RECEIVED"
};

module.exports = BenchConstants;
